### ISSUE TITLE
template/generic instantiation of `insert` from here

### ISSUE THREAD

**Issue by huaxk** [moigagoo/norm#27] opened 2019-09-11 03:30 UTC
I try build the example on nim 0.20.2:

```
import norm/sqlite
import logging
import unicode, sugar, options

db("petshop.db", "", "", ""):
  type
    User = object
      age: Positive
      name: string
      ssn: Option[int]

addHandler newConsoleLogger()

withDb:
  createTables(force=true)

withDb:
  var bob = User(
    age: 23,
    name: "bob",
    ssn: some 456
  )
  bob.insert()
  dump bob.id     
  debug(bob.id)
```

got build errors:

```
d:\sources\nim\main.nim(17, 1) template/generic instantiation of `withDb` from here
d:\sources\nim\main.nim(23, 6) template/generic instantiation of `insert` from here
C:\Users\user\.nimble\pkgs\norm-1.0.15\norm\sqlite.nim(90, 42) Error: attempting to call undeclared routine: 'join'
```

I try to commet line 90:
`debug insertQuery, " <- ", params.join(", ")`
in C:\Users\user\.nimble\pkgs\norm-1.0.15\norm\sqlite.nim

It can be compiled successes.

**Comment by moigagoo** [comment] 2019-09-11 06:27
This should be fixed with https://github.com/moigagoo/norm/commit/65d80919ffe8b654ef651e46241d18da8823ec0b

Could you please try to install norm@#develop and see if the issue persists?

**Comment by moigagoo** [comment] 2019-09-11 18:51
Should be fixed in 1.0.16.

**Closed by moigagoo** 2019-09-11 18:51 UTC
Labels: bug

**Comment by huaxk** [comment] 2019-09-12 03:25
Thanks for your response, The code above can be compiled.

add code as follows:
```
withDb:
  let bobs = User.getMany(
    100,
    cond="name LIKE 'Bob%' ORDER BY age"
  )

  dump bobs
```
got build errors:
```
d:\sources\nim\main.nim(31) main
C:\Users\user\.nimble\pkgs\norm-1.0.16\norm\sqlite.nim(167) getMany
C:\Users\user\.nimble\pkgs\norm-1.0.16\norm\sqlite\rowutils.nim(105) getMany
D:\scoop\apps\nim\current\lib\system\fatal.nim(48) sysFatal
Error: unhandled exception: i is not accessible [FieldError]
Error: execution of an external program failed: 'd:\sources\nim\main.exe '
```
The problem could be line 105:
 `     obj.dot(field) = row[i].i.int`
 in C:\Users\hxk\.nimble\pkgs\norm-1.0.16\norm\sqlite\rowutils.nim,
the type of field age in User is Positive, but row[i] DBValue has no i field.

**Comment by moigagoo** [comment] 2019-09-12 03:52
Could you please check the type of "age" column? I think it's TEXT because of these lame conditions here: https://github.com/moigagoo/norm/blob/develop/src/norm/sqlite/sqlgen.nim#L58

Apparently, it used to work before switch to ndb when I wrote this sample, even though it was wrong to store Positive in TEXT then too.

I've been trying to rewrite those ugly string comparisons to proper type checks but I just can't do that. I can’t get the type at this point in the program. If you have any advice, please share!

As of now, if my hypothesis is confirmed, I'll add Positive, Natural, and some more number types in this proc to make it work. And I will probably add this entire code sample to the test suite.

**Comment by moigagoo** [comment] 2019-09-12 03:52
Also, could you please create a separate issue on the second problem?

**Comment by kidandcat** [comment] 2019-10-11 08:42
This still happens to me:

```
C:\Users\jairo\Desktop\kidandcat.me\normtest.nim(21, 1) template/generic instantiation of `withDb` from here
C:\Users\jairo\Desktop\kidandcat.me\normtest.nim(25, 8) template/generic instantiation of `insert` from here
C:\Users\jairo\.nimble\pkgs\norm-1.0.17\norm\sqlite.nim(88, 23) template/generic instantiation of `toRow` from here
C:\Users\jairo\.nimble\pkgs\norm-1.0.17\norm\sqlite\rowutils.nim(301, 17) Error: type mismatch: got <seq[DbValue], string>
but expected one of:
proc add[T](x: var seq[T]; y: openArray[T])
  first type mismatch at position: 2
  required type for y: openArray[T]
  but expression 'capitalize(it)' is of type: string
proc add[T](x: var seq[T]; y: T)
  first type mismatch at position: 2
  required type for y: T
  but expression 'capitalize(it)' is of type: string
8 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them
```

**Comment by moigagoo** [comment] 2019-10-11 10:17
@kidandcat Sorry, I forgot to update the README and docstrings for norm module after 1.0.12 release. You should put ? in front of capitalize.

Updated the README: https://github.com/moigagoo/norm 

Thank you for reporting the issue. Please report any other issues you encounter.
