### ISSUE TITLE
selectAll with Options fields fails

### ISSUE THREAD

**Issue by Clonkk** [moigagoo/norm#103] opened 2021-03-01 10:34 UTC
Using ``selectAll`` with Option field seems to throw an exception : 

```
/home/rcaillaud/.nimble/pkgs/norm-2.2.3/norm/postgres.nim(213) selectAll
/home/rcaillaud/.nimble/pkgs/norm-2.2.3/norm/postgres.nim(203) select
/home/rcaillaud/.nimble/pkgs/norm-2.2.3/norm/private/postgres/rowutils.nim(51) fromRow
/home/rcaillaud/.nimble/pkgs/norm-2.2.3/norm/private/postgres/rowutils.nim(38) fromRowPos
/home/rcaillaud/.nimble/pkgs/norm-2.2.3/norm/private/postgres/dbtypes.nim(65) to
/home/rcaillaud/.choosenim/toolchains/nim-1.4.4/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: 'i' is not accessible using discriminant 'kind' of type 'DbValue' [FieldDefect]
```

This is the case I was able to minimize : 
```nim
type
  Toy* = ref object of Model
    price*: float

  Pet* = ref object of Model
    species*: string
    favToy*: Toy

  Person* = ref object of Model
    name* {.unique.}: string
    pet*: Option[Pet]

proc newToy(): Toy =
  Toy(price: 0.0)

proc newPet(): Pet =
  Pet(species: "cat", favToy: newToy())

proc newPerson(): Person =
  Person(name: "Bob", pet: none(Pet))

proc readAllData() =
  var humans = @[newPerson()]
  withDb:
    db.selectAll(humans)   # Error


proc readData() =
  var human = newPerson()
  withDb:
    db.select(human, "id=$1", 1)
  # OK

proc createDb() =
  withDb:
    db.createTables(newToy())
    db.createTables(newPet())
    db.createTables(newPerson())

proc dropDb() =
  withDb:
    dropDb()

proc insertData() =
  var toy = Toy(price: rand(100.0))
  var buddy = Pet(species: "dog", favToy: toy)
  var h1 = Person(name: "Jean", pet: some(buddy))
  var h2 = Person(name: "Rachel", pet: none(Pet))

  withDb:
    db.insert(h1)
    db.insert(h2)

proc main() =
  # createDb()
  insertData() # Careful about double insertion
  readData()
  readAlldata()
  # dropDb()

when isMainModule:
  main()

```

Fails with both SQLite and Postgres backend. Changing ``Person`` to use ``Pet`` field instead of ``Option[Pet]`` removes the error.

**Comment by moigagoo** [comment] 2021-03-01 16:50
Thanks for the report!

It has nothing to do with `selectAll`, the issue reproduces with `db.select(human, "id=$1", 2)`. I'll investigate.

**Comment by moigagoo** [comment] 2021-03-01 18:29
It’s so weird. I remember fixing this issue, even have a specific test for it, tnull.nim.

**Comment by moigagoo** [comment] 2021-03-01 19:09
Got it! The problem is that your container instance for `Person` has `none Pet` for `pet`, which means it's not a very good container: it can't possibly contain a value for `pet` should it be given to it by the DB. In a particular case where `pet` is NULL, it seems to fit `none Pet` right but if it's not a NULL but a proper id, there's nowhere to store the `Pet` instance.

So, I think we need a better error message rather than a fix.

**Comment by moigagoo** [comment] 2021-03-01 19:12
Working `readData` example:
```
proc readData() =
  var human = newPerson()
  human.pet = some newPet()               # Note that `pet` is not None and can actually hold a value if it's given to it.
  withDb:
    db.select(human, "Person.id=$1", 2) # Also, `id` is ambiguous since Person, Pet, and Toy tables all have it.
```

**Comment by moigagoo** [comment] 2021-03-01 19:14
Oops, correction. In the docs, I have the following statement:

> However, if the container has a none Model field, it is just ignored.

Which means that the original code mustn't break, and it's a bug indeed.

**Comment by moigagoo** [comment] 2021-03-01 19:23
Nah, just gave it some more thought. We can't possibly handle `none Model` container fields because without a `Model` instance at hand, we don't know how many row items need to be skipped.

It's the docs who are wrong, not the observed behaviour.

**Comment by moigagoo** [comment] 2021-03-01 20:36
I should stop coding late at night, my head is no good anymore.

It’s a bug that needs fixing, and I’ve just merged a dumb ass PR. Will roll ot back tomorrow.

**Comment by Clonkk** [comment] 2021-03-01 21:04
There's no hurry but I just had a similar error when trying to reduce #104.

**Closed** 2021-03-02 07:28 UTC
Labels: bug
